<style>
    label
    {
        width: 90px;
    }
    ul
    {
        list-style: none;
        margin-left: 0px;
        width: 190px;
    }
    li
    {
        margin: 2px;
        font-size: 11px;
    }
    input
    {
        width: 230px;
    }
    #login-element
    {
        text-align: center;
    }
    #login-label
    {
        display: none;
    }
</style>  
<script>
    $(document).ready(function(){
        $('.errors').addClass('alert alert-error');
        $('li').prepend("<b>Error:</b>");
    
    });
</script>
<div style="margin:0 auto 0 auto; width:330px;">
<?php echo $this->form; ?>
</div>