<!DOCTYPE html>
<html>
    <head>
        <title>::Matricula FIEI::</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="Author" content="Francis Gonzales" />
        <link rel="stylesheet" href="/css/modal.css" type="text/css" />
        <link type="text/css" href="/css/jquery-ui-1.8.12.custom.css" rel="stylesheet" />  
        <link type="text/css" href="/css/default.css" rel="stylesheet" />  
        <link type="text/css" href="/css/ui.jqgrid.css" rel="stylesheet" />  
        <link type="text/css" href="/css/bootstrap.min.css" rel="stylesheet" />  
        <script type="text/javascript" src="/javascript/jquery-1.7.2.min.js"></script>  
        <script type="text/javascript" src="/javascript/jquery-ui-1.8.12.custom.min.js"></script>  
        <script type="text/javascript" src="/javascript/jquery.ui.datepicker-es.js"></script>
        <script type="text/javascript" src="/javascript/i18n/grid.locale-es.js"></script>
        <script type="text/javascript" src="/javascript/jquery.jqGrid.min.js"></script> 
        <script type="text/javascript" src="/javascript/bootstrap.min.js"></script> 
    </head>
    <body> 
        <div id="wrapper">
            <div id="leyenda_div">
                <div id="unfv">
                    <a style="color:#FFF" target="_self" href="http://www.unfv.edu.pe/site/">Universidad Nacional Federico Villarreal</a>
                  </div>
                <div id="fecha"> 
                    Martes, 29 de Mayo del 2012 
                </div>
            </div>
            <div id="top" style="height: 243px;">
                <div id="header-no" >
                    <object width="980" height="200" title="banner principal" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000">
                        <param value="/images/bannerfier.swf" name="movie">
                        <param value="high" name="quality">
                        <param value="transparent" name="wmode">
                        <param value="transparent" name="wmode">
                        <embed width="980" height="200" wmode="transparent" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash" quality="high" src="/images/bannerfier.swf">
                    </object>
                </div>
                <div id="horiznav" class="horiznav">

                </div>
            </div>
            <div id="contenido" >
                <?php echo $this->layout()->content; ?>
            </div>

            <div id="footer" >
                <div id="foot">
                    <div class="ro">
                        <div class="ce ce1 cel w12">
                            <div class="co1b1 co coa2 coc1 m3 footer2">
                                <div class="br br1">
                                    <div class="msnfoot1 cf">
                                        <div class="left_primary">
                                            <span class="primary">
                                                <a href="http://www.unfv.edu.pe">UNFV</a>
                                                ,
                                                <a href="http://www.unfv.edu.pe/facultades/fiei/">Facultad de Ingeniería Electrónica e Informática</a>
                                            </span>
                                            <br>
                                            <span>Jr. Iquique Nº 127 - Breña-Lima.</span>
                                            <br>
                                            <span>Telefóno: 720 9720 Anexo 9871, 9866</span>
                                        </div>
                                        <a class="copyright" href="http://www.unfv.edu.pe">
                                            <span>&copy; 2012 UNFV</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</html>
